import React, { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { MitreAPI } from "../api/mitre";
import { AlertsAPI } from "../api/alerts";
import { Card } from "../components/ui/Card";
import { HeatmapGrid } from "../components/mitre/HeatmapGrid";
import { HeatmapLegend } from "../components/mitre/HeatmapLegend";
import { HeatmapControls } from "../components/mitre/HeatmapControls";
import type { MitreHeatmapResponse } from "../types/mitre";

export function MitreHeatmapPage() {
  const [showOnlyCovered, setShowOnlyCovered] = useState(false);
  const [timeWindow, setTimeWindow] = useState<"24h" | "7d" | "30d" | "all">("all");

  const heatmapQ = useQuery({
    queryKey: ["mitre", "heatmap"],
    queryFn: () => MitreAPI.heatmap(),
  });

  const alertsQ = useQuery({
    queryKey: ["alerts"],
    queryFn: () => AlertsAPI.list(),
  });

  const playbooksQ = useQuery({
    queryKey: ["playbooks"],
    queryFn: () => AlertsAPI.listPlaybooks(),
  });

  const exportRows = useMemo(() => {
    const d = heatmapQ.data as MitreHeatmapResponse | undefined;
    if (!d) return [];

    // Export full technique list with tactic, technique_id, name, count (current counts shown on UI are computed in HeatmapGrid)
    // We'll export backend counts (all-time playbook-driven) as baseline.
    const rows: Array<Record<string, any>> = [];
    for (const g of d.tactics || []) {
      for (const t of g.tiles || []) {
        rows.push({
          tactic: g.tactic,
          technique_id: t.technique_id,
          technique_name: t.technique_name,
          count_backend_all_time: t.count,
        });
      }
    }
    return rows;
  }, [heatmapQ.data]);

  return (
    <Card>
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold">MITRE Heatmap</h1>
          <div className="text-sm text-neutral-400">
            Evidence-based (playbook-driven) ATT&CK coverage
          </div>
        </div>
      </div>

      {/* Explanation + collapsibles */}
      <div className="mt-6 rounded-xl border border-neutral-800 bg-neutral-900/40 p-5 space-y-4">
        <div className="flex flex-col gap-3">
          <div>
            <div className="text-sm font-semibold text-neutral-200">How to read this map</div>
            <p className="mt-2 text-sm text-neutral-300 leading-relaxed">
              MITRE ATT&CK organizes adversary behavior into <span className="text-neutral-100 font-medium">tactics</span> (columns)
              and <span className="text-neutral-100 font-medium">techniques</span> (tiles). This heatmap highlights where your SOC has
              <span className="text-neutral-100 font-medium"> operational response coverage</span>.
            </p>
            <p className="mt-2 text-sm text-neutral-300 leading-relaxed">
              Coverage here is <span className="text-neutral-100 font-medium">playbook-driven</span>: a technique is counted only when
              there is an alert *and* an associated remediation playbook. This reduces false confidence from “detection-only” coverage.
            </p>
          </div>

          <div className="rounded-lg border border-neutral-800 bg-neutral-950/40 p-3">
            <div className="text-xs text-neutral-400 mb-2">Color legend (alert frequency with playbooks)</div>
            <HeatmapLegend />
          </div>

          <details className="rounded-lg border border-neutral-800 bg-neutral-950/30 p-3">
            <summary className="cursor-pointer text-sm text-neutral-200 font-medium">
              About the AI playbooks and confidence scoring
            </summary>
            <div className="mt-2 text-sm text-neutral-300 leading-relaxed space-y-2">
              <p>
                Playbooks are generated by a local LLM with strict JSON output enforcement. To reduce hallucinations, the system uses
                Retrieval-Augmented Generation (RAG) over curated SOC knowledge articles.
              </p>
              <p>
                <span className="text-neutral-100 font-medium">Confidence</span> reflects the average similarity score of retrieved
                knowledge snippets used during generation (higher similarity → higher confidence). You can inspect the exact snippets
                used under each playbook.
              </p>
            </div>
          </details>

          <details className="rounded-lg border border-neutral-800 bg-neutral-950/30 p-3">
            <summary className="cursor-pointer text-sm text-neutral-200 font-medium">
              Evidence-based coverage rule (why it matters)
            </summary>
            <div className="mt-2 text-sm text-neutral-300 leading-relaxed space-y-2">
              <p>
                Many dashboards count coverage when an alert is mapped to MITRE, even if no response procedure exists.
                This project intentionally counts coverage only when a playbook exists, because playbooks represent
                validated remediation steps.
              </p>
              <p className="text-xs text-neutral-500">
                Tip: Click an alert count on any technique to open the list of underlying alerts and playbooks.
              </p>
            </div>
          </details>
        </div>
      </div>

      {/* Controls */}
      <div className="mt-6 flex items-center justify-between gap-4">
        <HeatmapControls
          showOnlyCovered={showOnlyCovered}
          setShowOnlyCovered={setShowOnlyCovered}
          timeWindow={timeWindow}
          setTimeWindow={setTimeWindow}
          exportRows={exportRows}
        />
      </div>

      {/* Heatmap */}
      <div className="mt-6">
        {heatmapQ.isLoading || alertsQ.isLoading || playbooksQ.isLoading ? (
          <div className="text-neutral-400">Loading heatmap…</div>
        ) : heatmapQ.error ? (
          <div className="text-red-500">Failed to load heatmap. Make sure backend is running.</div>
        ) : (
          <HeatmapGrid
            data={heatmapQ.data ?? null}
            showOnlyCovered={showOnlyCovered}
            timeWindow={timeWindow}
            alerts={alertsQ.data ?? []}
            playbooks={playbooksQ.data ?? []}
          />
        )}
      </div>
    </Card>
  );
}